### ISSUE TITLE
Ambiguous use of init when using XCode Cloud

### ISSUE THREAD

**Issue by femmedecentral** [rollbar/rollbar-react-native#199] opened 2024-10-03 05:20 UTC
I've been using Rollbar / Rollbar ReactNative successfully for some time, including using it as part of my automatic build pipeline in XCode Cloud. I've been working on things unrelated to Rollbar for the last couple of months and am trying to create a new build using XCode Cloud, and the only errors I seem to be running into with the new build are related to the Rollbar library / integration. 

First, I ran into this issue:
```
RollbarCrash

Error
No type named 'set_terminate' in namespace 'std'
RollbarCrashMonitor_CPPException.cpp:223

Error
No type named 'terminate_handler' in namespace 'std'
RollbarCrashMonitor_CPPException.cpp:66

Error
No member named 'set_terminate' in namespace 'std'
RollbarCrashMonitor_CPPException.cpp:219
```

But I found a couple of workarounds, either adding `pod 'RollbarNotifier', '~> 3.3.2' `
or adding

```
if [target.name](http://target.name/) == 'RollbarCrash'
        file_path = 'Pods/RollbarCrash/RollbarNotifier/Sources/RollbarCrash/Monitors/RollbarCrashMonitor_CPPException.cpp'
        contents = File.read(file_path)
        unless contents.include?('#include <exception>')
          File.open(file_path, 'w') do |file|
            file.puts('#include <exception>')
            file.puts(contents)
          end
        end
      end
```

to the post install phase of my podfile seemed to clear that up, but now I'm stuck on a new issue:

```
RollbarReport

Error
Ambiguous use of 'init'
BinaryImage.swift:44

Error
Ambiguous use of 'init'
Report.swift:86
```

Nothing I do seems to work around this. I've tried updating from "rollbar-react-native": "1.0.0-beta.2" to "rollbar-react-native": "1.0.0-beta.4" and back around, reinstalling both rollbar and rollbar-react-native and nothing seems to help. I can build an archive locally using XCode, but I'd much prefer if my XCode Cloud process works because it has all the correct configs to package a build for production.

**Comment by airowe** [comment] 2024-10-11 15:24
Seeing this locally using xCode 16

**Comment by feng-yu-healthbank** [comment] 2024-10-15 01:45
Builds started to fail after Xcode was automatically updated to 16 on a physical macbook.

**Comment by claudiozam** [comment] 2024-10-20 12:15
Same issue: xcode 16 and RN 0.76-rc6

**Comment by tawanhealthbank** [comment] 2024-10-22 08:45
Same here, issue on OS 15.0.1.

**Comment by rares-lupascu** [comment] 2024-10-23 18:30
same here

**Comment by rares-lupascu** [comment] 2024-10-23 20:41
whoever wants a temporary fix ... in ur Podfile ... update the post_install hook like
```ruby
  post_install do |installer|
    # ...other code
    file_path = 'Pods/Rollbar/KSCrash/Source/KSCrash/Recording/Monitors/KSCrashMonitor_CPPException.cpp'
    system("sed -i '' '/#include <typeinfo>/a\\
    #include <exception>
    ' #{file_path}")
  end
```
then clean and rebuild

**Comment by matux** [comment] 2024-10-23 23:11
Hey all, Rollbar dev here.

There seems to be two compilation issues being reported here, 

1. one related to a missing `#include` in some `cpp` file which is causing the build to fail.
***This issue has been fixed in latest version `1.0.0-beta.4` uses the `rollbar-apple` 3.3.2 SDK:***
https://github.com/rollbar/rollbar-react-native/blob/5473cb2b4af7f5f2b3c27a78061445a2590b109d/RollbarReactNative.podspec#L17

Which already has that fix:
https://github.com/rollbar/rollbar-apple/blob/c89ed08a441a4ac079fac793e9fb9aaf430cff19/RollbarNotifier/Sources/RollbarCrash/Monitors/RollbarCrashMonitor_CPPException.cpp#L42-L43

The fix was introduced in this PR: https://github.com/rollbar/rollbar-apple/pull/349.

If you're on the latest version of `rollbar-react-native`, you should have the code that corresponds to the `rollbar-apple` 3.3.2 release.

---

2. Then, there seems to be another compilation issue with an ambiguous `URL.init` that I'm currently unable to reproduce when building locally using Xcode, so I will be digging further soon to understand and fix this issue.

Thank you all for your patience!

**Comment by matux** [comment] 2024-10-24 17:24
I'm unable to reproduce any of these issues when using the latest `rollbar-react-native` SDK `1.0.0-beta.4`, with or without Xcode Cloud.

Make sure you're on the latest version of the SDK, and `pod update` your `ios` directories where your native ios application `.xcproject`/`.xcworkspace` files reside.

If you keep seeing this issue, would it be possible to either share an example project or more details about how your project is set up so that I can trigger this issue. Pinpointing the problem without being able to reproduce it is very difficult.

Thank you, all!

**Comment by claudiozam** [comment] 2024-10-25 11:28
Hi @matux , thank you for your response. Example repo with the error **Ambiguous use of init**.

https://github.com/claudiozam/rollbar-error

<img width="1570" alt="image" src="https://github.com/user-attachments/assets/695de3f5-7b88-4b08-b69e-c5e4fc32a719">


My dev. enviroment. The rest is in the repo (RN 0.76 + Rollbar RN 1.0.0-beta.4)


```
  System:
    OS: macOS 15.0.1
    CPU: (12) arm64 Apple M2 Max
    Memory: 15.95 GB / 64.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 22.10.0 - /opt/homebrew/bin/node
    Yarn: 1.22.22 - /opt/homebrew/bin/yarn
    npm: 10.9.0 - /opt/homebrew/bin/npm
  Managers:
    CocoaPods: 1.15.2 - /Users/claudiozamoszczyk/.rvm/gems/ruby-3.1.4@fastlane/bin/pod
    Homebrew: 4.4.2 - /opt/homebrew/bin/brew
    pip3: 24.2 - /opt/homebrew/bin/pip3
    RubyGems: 3.3.26 - /Users/claudiozamoszczyk/.rvm/rubies/ruby-3.1.4/bin/gem
  Utilities:
    Make: 3.81 - /usr/bin/make
    GCC: 16.0.0 - /usr/bin/gcc
    Git: 2.47.0 - /opt/homebrew/bin/git
    Clang: 16.0.0 - /usr/bin/clang
    Curl: 8.7.1 - /usr/bin/curl
    OpenSSL: 3.3.2 - /opt/homebrew/bin/openssl
  SDKs:
    iOS SDK:
      Platforms: DriverKit 24.0, iOS 18.0, macOS 15.0, tvOS 18.0, visionOS 2.0, watchOS 11.0
  IDEs:
    Xcode: 16.0/16A242d - /usr/bin/xcodebuild
  Languages:
    Bash: 3.2.57 - /bin/bash
    Java: 17.0.13 - /opt/homebrew/opt/openjdk@17/bin/javac
    Perl: 5.34.1 - /usr/bin/perl
    Python3: 3.13.0 - /opt/homebrew/bin/python3
    Ruby: 3.1.4 - /Users/claudiozamoszczyk/.rvm/rubies/ruby-3.1.4/bin/ruby
  
```


@tawanorg thanks for your example repo.

**Comment by matux** [comment] 2024-10-25 12:48
@tawanorg @claudiozam This is great! Much appreciated, guys. I'll look into this today and get a fix for you asap.

**Comment by matux** [comment] 2024-10-25 14:24
I believe I've found the problem, I'm going to do my best to make a release today.

**Comment by matux** [comment] 2024-10-25 19:44
Alright, [`rollbar-react-native` 1.0.0-beta.5](https://www.npmjs.com/package/rollbar-react-native) is out.

This should take care of the `URL.init` compilation issues you're experiencing.

However, there's also two things you should change from your `ios/Podfile` files I've seen in both example repos shared.

First of all, remove these lines:
```
  # Rollbar dependencies
  pod 'RollbarReport'
  pod 'RollbarCrash', :modular_headers => true
```
I understand Cocoapods suggests doing this, but these aren't necessary and messes with the internal configuration of `RollbarCrash`, which leads the the `-objc` issues.

And second, make sure you have this line in the same Podfile:
`use_frameworks! :linkage => :static`

This is an example of one of a working Podfile I modified from one of the repository you guys shared:
```rb
❯ cat ./ios/Podfile
# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

use_frameworks! :linkage => :static ### This is the only line you need to add.

target 'hb' do
  config = use_native_modules!

  pod 'RollbarReactNative', path: '../node_modules/rollbar-react-native'

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'hbTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )
  end
end
```

There's a tidier way of doing this which involves making sure the `USE_FRAMEWORKS` dev env is passed with the 'static' value. But what I'm showing here should work.

Also, remember to go into your `ios` directory and run `pod update` because `npm run ios` doesn't seem to be doing any of that. This will ensure you get the latest RollbarNotifier 3.3.3 version and that everything gets statically linked.

Once you do that, you can go back to your project root and run `npm run ios` and things should run smoothly:
```
❯ npm run ios

> hb@0.0.1 ios
> react-native run-ios

info A dev server is already running for this project on port 8081.
info Found Xcode workspace "hb.xcworkspace"
info Found booted iPhone SE (3rd generation)
info Building (using "xcodebuild -workspace hb.xcworkspace -configuration Debug -scheme hb -destination id=56ADC2DC-7B4D-46F4-A127-EA47B59BFA08")
success Successfully built the app
--- xcodebuild: WARNING: Using the first of multiple matching destinations:
{ platform:iOS Simulator, id:dvtdevice-DVTiOSDeviceSimulatorPlaceholder-iphonesimulator:placeholder, name:Any iOS Simulator Device }
{ platform:iOS Simulator, id:30072894-26D6-450D-B2A0-12C792AB6EDB, OS:17.5, name:iPad (10th generation) }
{ platform:iOS Simulator, id:30072894-26D6-450D-B2A0-12C792AB6EDB, OS:17.5, name:iPad (10th generation) }
...
{ platform:iOS Simulator, id:E2A625A8-387E-456F-BD04-229B284A904F, OS:18.1, name:iPhone SE (3rd generation) }
{ platform:iOS Simulator, id:E2A625A8-387E-456F-BD04-229B284A904F, OS:18.1, name:iPhone SE (3rd generation) }
{ platform:visionOS Simulator, variant:Designed for [iPad,iPhone], id:5B6BF96E-B4AD-43B7-A244-430E754C3F60, OS:2.0, name:Apple Vision Pro }
{ platform:macOS, arch:arm64, variant:Designed for [iPad,iPhone], id:00006001-001048CA0204401E, name:My Mac }
{ platform:iOS, id:dvtdevice-DVTiPhonePlaceholder-iphoneos:placeholder, name:Any iOS Device }
info Installing "/Users/matux/Library/Developer/Xcode/DerivedData/hb-cygzjpzpffjvcigxjgmqrzauvkxg/Build/Products/Debug-iphonesimulator/hb.app
info Launching "org.reactjs.native.example.hb"
success Successfully launched the app
``

**Comment by matux** [comment] 2024-10-25 19:49
I'll close this issue as soon as you guys confirm you got things working on your side. Any other issue you may be seeing, don't hesitate communicating, I'll do my best to fix things asap for all of you.

I really appreciate the example repositories you guys shared, they were instrumental in me understanding what was going on.

We'll also be updating our documentation soon to make things clearer for you guys.

**Comment by matux** [comment] 2024-11-01 16:39
I'm closing this issue as it seems things are working again.

**Closed by matux** 2024-11-01 16:39 UTC
