### ISSUE TITLE
[iOS] Build failed for 0.2.0-alpha3

### ISSUE THREAD

**Issue by dwilt** [rollbar/rollbar-react-native#12] opened 2018-01-17 18:58 UTC
I'm getting this error after upgrading:

![image](https://user-images.githubusercontent.com/1065539/35061201-548f736c-fb75-11e7-9a28-50ed163d26b6.png)

I tried to `unlink` and reattached the new `Rollbar.framework` package and did a clean on the project. Any ideas?

**Comment by Gurpreetgpsingh** [comment] 2018-01-23 12:00
Am facing compile time error : "'Rollbar/Rollbar.h' file not found" in RollbarReactNative.h file in Xcode 9.2 
But if I change "#import <Rollbar/Rollbar.h>" to #import <Rollbar.framework/Headers/Rollbar.h> in RollbarReactNative.h file then am getting same error as mentioned by @dwilt  
![rollbar error](https://user-images.githubusercontent.com/22536395/35274665-f1a59dba-0062-11e8-86ca-99e88a799a80.png)

**Comment by rokob** [comment] 2018-01-25 01:56
Did you add the framework to the RollbarReactNative project within the react native workspace as described in the readme?

**Comment by Gurpreetgpsingh** [comment] 2018-01-29 07:48
Yes @rokob 
I have followed these steps:
![rollbar steps](https://user-images.githubusercontent.com/22536395/35499045-d83d09a6-04f6-11e8-98ee-71f82cb00260.png)

**Comment by jasongaare** [comment] 2018-01-31 15:17
I am also getting the same errors as above. I'm assuming it has something to do with header search paths, or framework search paths, but haven't been able to get a correct configuration for it to build successfully

**Comment by rokob** [comment] 2018-02-05 21:30
Huzzah I've at least got this reproduced, working on a fix.

**Comment by jasongaare** [comment] 2018-02-21 15:06
@rokob is there an update on this?

**Comment by rokob** [comment] 2018-02-21 20:00
The issue is the underlying Rollbar iOS library framework that gets generated is broken for some reason. I got distracted by some other things but I'm back on this now. The framework we generate appears to have all the symbols in the fat binary that we generate (by inspect the binary), but for some reason the linker hates me.

**Comment by jasongaare** [comment] 2018-02-21 21:07
No worries. I know what a pain in the ass getting iOS to link things correctly is -- appreciate your work on this!

**Comment by rokob** [comment] 2018-02-23 19:27
Okay, there is a new release up of the rollbar-ios library (https://github.com/rollbar/rollbar-ios/releases/tag/v1.0.0-alpha6) with a new zip file.

In a normal iOS app you would need to add `libc++` to your link binary with libraries phase and add `-ObjC` to your "Other Linker Flags" section. However both of these should already be there in React Native, but if you get any weird C++ errors or missing selector exceptions then double check those two things.

There was a problem with the build process that generated the framework binary that I believe is now fixed. I'm going to leave this open issue for a bit in case other problems arise.

**Closed** 2018-03-02 18:49 UTC
