### ISSUE TITLE
Package causes build fail for iOS (Arm64/Apple Silicon)

### ISSUE THREAD

**Issue by marcfrankel** [rollbar/rollbar-react-native#173] opened 2023-03-07 23:55 UTC
This package currently does not work when building for iOS on an apple silicon based Mac (without using Rosetta).

Forgive me if this is already known or is currently never planned to be supported. But as I recently switched to apple silicon I find myself unable to use this package in the builds I make.

I wanted to provide better logs for you, but helpful logs seem to come and go during the build process. All I know right now is that if I include this package my build fails with the following output. And if I remove this package and _only_ this package the build succeeds.

```
(/Users/[Redacted]/Library/Developer/Xcode/DerivedData/[redacted]-clcsbmsuwkuytofkihwacgauhokl/Build/Products/Debug-iphonesimulator/ExpoModulesCore/ExpoModulesCore.framework/Headers/ExpoModulesCore-Swift.h:499:2)

  497 | 
  498 | #else
> 499 | #error unsupported Swift architecture
      |  ^ unsupported Swift architecture
  500 | #endif
  501 | 
```

my xcodebuild-error.log file also contains this:

```
** BUILD FAILED **


The following build commands failed:
	SwiftEmitModule normal x86_64 Emitting\ module\ for\ [redacted] (in target '[Redacted]' from project '[Redacted]')
(1 failure)
```

Hopefully this is enough to go on to make this package Apple Silicon compatible. I might be forced to switch otherwise. Happy to provide any additional info! Thanks.

**OTHER INFO:**
Expo SDK 48
React Native V 0.71.3
M2 Max Chip
Xcode Version 14.2
rollbar-react-native V 0.9.3

**Comment by rollbar-bborsits** [comment] 2023-03-08 13:35
Hey @marcfrankel, Thanks for reporting this issue. The details you shared will help us to look into it thoroughly. Our React Native SDK still uses our [iOS SDK](https://github.com/rollbar/rollbar-ios) that has some incompatibility issues. I suspect that causes your issue here, but that needs to be confirmed. We plan to mitigate the issues with our iOS SDK by introducing a new, state of the art [Apple SDK](https://github.com/rollbar/rollbar-apple). We plan to release the new Apple SDK soon and we'll update the React Native package too afterwards. The new Apple SDK meant to be fully compatible with Swift. I'll keep you posted.

**Comment by cseelus** [comment] 2023-03-10 12:45
Hm, so since Expo since SDK 48 uses Apple silicon for `eas-build`, using Rollbar here is not an option currently, it seems.

**Comment by rollbar-bborsits** [comment] 2023-03-31 16:26
We released the fresh version of our Apple SDK yesterday. https://github.com/rollbar/rollbar-apple/releases/tag/3.0.0
We'll update our React Native SDK during the following weeks.

**Comment by marcfrankel** [comment] 2023-03-31 17:09
Awesome! Love to hear it.

**Comment by kdutcher** [comment] 2023-05-17 14:49
Checking in to see if there is timeline or progress. Thanks!

**Comment by waltjones** [comment] 2023-05-17 17:16
This is the last remaining item for the upcoming release, so the good news is once this is ready, nothing else should be blocking immediate release.

I've self-assigned this issue, and will link the PR and release here.

**Comment by waltjones** [comment] 2023-06-20 20:25
Sincere apologies for the inconvenience. The rollbar-apple maintainer needed to make some changes to enable Cocoapods. That's done, and I will get a release out very soon.

**Comment by cseelus** [comment] 2023-06-20 23:16
> […] changes to enable Cocoapods. That's done, and I will get a release out very soon.

Will it be compatible with React Native apps, using Expo (managed workflow)?

**Comment by waltjones** [comment] 2023-06-21 20:06
The upcoming release has been updated to work with JS-only apps (https://github.com/rollbar/rollbar-react-native/pull/171), and has been tested with Expo.

**Comment by waltjones** [comment] 2023-07-11 18:43
v1.0.0-beta.0 is now available. https://github.com/rollbar/rollbar-react-native/releases/tag/v1.0.0-beta.0

This is expected to be fully compatible with iOS build targets, as well as web-only and [@rollbar/react](https://www.npmjs.com/package/@rollbar/react). Please report any issues. Note that there are breaking changes between v0.9.3 and this 1.0.0 beta. See the [updated SDK guide](https://docs.rollbar.com/docs/react-native) and the [migration guide](https://docs.rollbar.com/docs/migrating-to-v100) for details.

**Closed** 2023-12-18 17:45 UTC
